In [1]:
#pip install opencv-python

In [2]:
#img.shape -> imprimir la longitud de la matriz
#img -> imprimir la matriz
#show -> imprimir la imagen
#read -> leer la imagen


In [3]:
import numpy as np
from numpy import *
import matplotlib.pyplot as plt
import cv2

#print('log import libraries')

#mostrar imagen
show = lambda x: plt.imshow(x)
sign = lambda x: 1 if x>0 else -1 if x<0 else 0
read = lambda x: cv2.imread(x)

#convertir imagen a escala de grises
def convert_to_grayscale(x):
    y = x
    rows = x.shape[0]
    columns = x.shape[1]
    for i in range(rows):
        for j in range(columns):
            y[i, j] = sum(x[i, j])/3
    return y

def convert_grayscale_to_matrix(x):    
    rows = x.shape[0]
    columns = x.shape[1]    
    rows = 3
    columns = 3    
    #print('rows' , rows )
    #print('columns' , columns)    
    m = zeros((rows, columns))
    for i in range(rows):
        for j in range(columns):
            m[i,j] = x[i,j,0]
    return m

def add_boder_to_matrix(x):
    rows = x.shape[0]
    columns = x.shape[1]
    m = zeros((rows + 2 , columns + 2))
    for i in range(rows):
        for j in range(columns):
            m[i+1,j+1] = x[i,j]
    return m
    
def create_matrix_vector_diff_8(x):    
    rows = x.shape[0]
    columns = x.shape[1]    
    r = zeros((rows, columns, 8 ))    
    for i in range(1, rows-1):
        for j in range(1, columns-1):
            r[i][j][0] = sign( int( x[i][j] ) -  int( x[i-1][j  ] ) )
            r[i][j][1] = sign( int( x[i][j] ) -  int( x[i-1][j+1] ) ) 
            r[i][j][2] = sign( int( x[i][j] ) -  int( x[i  ][j+1] ) )
            r[i][j][3] = sign( int( x[i][j] ) -  int( x[i+1][j+1] ) )
            r[i][j][4] = sign( int( x[i][j] ) -  int( x[i+1][j  ] ) )
            r[i][j][5] = sign( int( x[i][j] ) -  int( x[i+1][j-1] ) )
            r[i][j][6] = sign( int( x[i][j] ) -  int( x[i  ][j-1] ) )
            r[i][j][7] = sign( int( x[i][j] ) -  int( x[i-1][j-1] ) )
    return r

def remove_boder_to_matrix_diff_8(x):
    rows = x.shape[0]
    columns = x.shape[1]
    r = zeros((rows - 2 , columns - 2, 8 ))  
    for i in range(1, rows-1):
        for j in range(1, columns-1):
            r[i-1,j-1] = x[i,j]
    return r

'''   
7 0 1
6 x 2
5 4 3
return r
''' 
#print('create_function')

def proceso():
    img = read('../Base/Train/c003_001.png')
    
    #show(img)
    #convertir en escala de grises
    
    img = convert_to_grayscale(img)
    
    #show(img)
    #print(img)
    
    ma = convert_grayscale_to_matrix(img)
    print('convert_grayscale_to_matrix')
    print(ma)
    print()
    
    ma = add_boder_to_matrix(ma)
    print('add_boder_to_matrix')
    print(ma)
    print()
    
    ma = create_matrix_vector_diff_8(ma)
    print('create_matrix_vector_diff_8')
    print(ma)
    print()
    
    ma = remove_boder_to_matrix_diff_8(ma)
    print('remove_boder_to_matrix')
    print(ma)
    print()
    
def main():
    print('Inicio')
    print()
    
    proceso()

    print()
    print('Fin')
main()    

Inicio

convert_grayscale_to_matrix
[[125. 122. 108.]
 [123. 120. 112.]
 [126. 124. 113.]]

add_boder_to_matrix
[[  0.   0.   0.   0.   0.]
 [  0. 125. 122. 108.   0.]
 [  0. 123. 120. 112.   0.]
 [  0. 126. 124. 113.   0.]
 [  0.   0.   0.   0.   0.]]

create_matrix_vector_diff_8
[[[ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1. -1. -1.  1.]
  [ 1.  1.  1.  1. -1. -1. -1.  1.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.]
  [-1.  1.  1. -1. -1.  1.  1.  1.]
  [-1.  1.  1.  1. -1. -1. -1. -1.]
  [ 1.  1.  1.  1. -1. -1. -1. -1.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.  1. -1.  1.]
  [ 1.  1.  1.  1.  1.  1. -1. -1.]
  [ 0.  0.  0.  0.  0.  0.  